const rathuadhab = {
    views: {
        view1: { src: require('./../../assets/Rathuadhab/views/view1.jpg'), caption: 'view 1' },
        view2: { src: require('./../../assets/Rathuadhab/views/view2.jpg'), caption: 'view 2' },
        view3: { src: require('./../../assets/Rathuadhab/views/view3.jpg'), caption: 'view 3' },
        view4: { src: require('./../../assets/Rathuadhab/views/view4.jpg'), caption: 'view 4' },
        view5: { src: require('./../../assets/Rathuadhab/views/view5.jpg'), caption: 'view 5' },
        view6: { src: require('./../../assets/Rathuadhab/views/view6.jpg'), caption: 'view 6' },
        view7: { src: require('./../../assets/Rathuadhab/views/view7.jpg'), caption: 'view 7' },
        view8: { src: require('./../../assets/Rathuadhab/views/view8.jpg'), caption: 'view 8' },
        view9: { src: require('./../../assets/Rathuadhab/views/view9.jpg'), caption: 'view 9' },
        view10: { src: require('./../../assets/Rathuadhab/views/view10.jpg'), caption: 'view 10' },
        view11: { src: require('./../../assets/Rathuadhab/views/view11.jpg'), caption: 'view 11' },
        view12: { src: require('./../../assets/Rathuadhab/views/view12.jpg'), caption: 'view 12' },
        view13: { src: require('./../../assets/Rathuadhab/views/view13.jpg'), caption: 'view 13' },
        view14: { src: require('./../../assets/Rathuadhab/views/view14.jpg'), caption: 'view 14' },
        view15: { src: require('./../../assets/Rathuadhab/views/view15.jpg'), caption: 'view 15' },
        view16: { src: require('./../../assets/Rathuadhab/views/view16.jpg'), caption: 'view 16' },
        view17: { src: require('./../../assets/Rathuadhab/views/view17.jpg'), caption: 'view 17' },
        view18: { src: require('./../../assets/Rathuadhab/views/view18.jpg'), caption: 'view 18' },
        view19: { src: require('./../../assets/Rathuadhab/views/view19.jpg'), caption: 'view 19' },
        view20: { src: require('./../../assets/Rathuadhab/views/view20.jpg'), caption: 'view 202' },
        view21: { src: require('./../../assets/Rathuadhab/views/view21.jpg'), caption: 'view 21' },
        view22: { src: require('./../../assets/Rathuadhab/views/view22.jpg'), caption: 'view 22' },
        view23: { src: require('./../../assets/Rathuadhab/views/view23.jpg'), caption: 'view 23' },
        view24: { src: require('./../../assets/Rathuadhab/views/view24.jpg'), caption: 'view 24' },
        view25: { src: require('./../../assets/Rathuadhab/views/view25.jpg'), caption: 'view 25' },
        view26: { src: require('./../../assets/Rathuadhab/views/view26.jpg'), caption: 'view 26' },
        view27: { src: require('./../../assets/Rathuadhab/views/view27.jpg'), caption: 'view 27' },
        view28: { src: require('./../../assets/Rathuadhab/views/view28.jpg'), caption: 'view 28' },
        view29: { src: require('./../../assets/Rathuadhab/views/view29.jpg'), caption: 'view 29' },
        view30: { src: require('./../../assets/Rathuadhab/views/view30.jpg'), caption: 'view 30' },
        view31: { src: require('./../../assets/Rathuadhab/views/view31.jpg'), caption: 'view 31' },
        view32: { src: require('./../../assets/Rathuadhab/views/view32.jpg'), caption: 'view 32' },
        view33: { src: require('./../../assets/Rathuadhab/views/view33.jpg'), caption: 'view 33' },
        view34: { src: require('./../../assets/Rathuadhab/views/view34.jpg'), caption: 'view 34' },
        view35: { src: require('./../../assets/Rathuadhab/views/view35.jpg'), caption: 'view 35' },
        view36: { src: require('./../../assets/Rathuadhab/views/view36.jpg'), caption: 'view 36' },
        view37: { src: require('./../../assets/Rathuadhab/views/view37.jpg'), caption: 'view 37' },
        view38: { src: require('./../../assets/Rathuadhab/views/view38.jpg'), caption: 'view 38' },
        view39: { src: require('./../../assets/Rathuadhab/views/view39.jpg'), caption: 'view 39' },
        view40: { src: require('./../../assets/Rathuadhab/views/view40.jpg'), caption: 'view 40' },
        view41: { src: require('./../../assets/Rathuadhab/views/view41.jpg'), caption: 'view 41' },
        view42: { src: require('./../../assets/Rathuadhab/views/view42.jpg'), caption: 'view 42' },
        view43: { src: require('./../../assets/Rathuadhab/views/view43.jpg'), caption: 'view 43' },
        view44: { src: require('./../../assets/Rathuadhab/views/view44.jpg'), caption: 'view 44' },
        view45: { src: require('./../../assets/Rathuadhab/views/view45.jpg'), caption: 'view 45' },
        view46: { src: require('./../../assets/Rathuadhab/views/view46.jpg'), caption: 'view 46' },
        view47: { src: require('./../../assets/Rathuadhab/views/view47.jpg'), caption: 'view 47' },
        view48: { src: require('./../../assets/Rathuadhab/views/view48.jpg'), caption: 'view 48' },
        view49: { src: require('./../../assets/Rathuadhab/views/view49.jpg'), caption: 'view 49' },
        view50: { src: require('./../../assets/Rathuadhab/views/view50.jpg'), caption: 'view 50' },
        view51: { src: require('./../../assets/Rathuadhab/views/view51.jpg'), caption: 'view 51' },
        view52: { src: require('./../../assets/Rathuadhab/views/view52.jpg'), caption: 'view 52' },
        view53: { src: require('./../../assets/Rathuadhab/views/view53.jpg'), caption: 'view 53' },
        view54: { src: require('./../../assets/Rathuadhab/views/view54.jpg'), caption: 'view 54' },
        view55: { src: require('./../../assets/Rathuadhab/views/view55.jpg'), caption: 'view 55' },
        view56: { src: require('./../../assets/Rathuadhab/views/view56.jpg'), caption: 'view 56' },
        view57: { src: require('./../../assets/Rathuadhab/views/view57.jpg'), caption: 'view 57' },
        view58: { src: require('./../../assets/Rathuadhab/views/view58.jpg'), caption: 'view 58' },
        view59: { src: require('./../../assets/Rathuadhab/views/view59.jpg'), caption: 'view 59' },
        view60: { src: require('./../../assets/Rathuadhab/views/view60.jpg'), caption: 'view 60' },
        view61: { src: require('./../../assets/Rathuadhab/views/view61.jpg'), caption: 'view 61' },
        view62: { src: require('./../../assets/Rathuadhab/views/view62.jpg'), caption: 'view 62' },
        view63: { src: require('./../../assets/Rathuadhab/views/view63.jpg'), caption: 'view 63' },
        view64: { src: require('./../../assets/Rathuadhab/views/view64.jpg'), caption: 'view 64' },
        view65: { src: require('./../../assets/Rathuadhab/views/view65.jpg'), caption: 'view 65' },
        view66: { src: require('./../../assets/Rathuadhab/views/view66.jpg'), caption: 'view 66' },
        view67: { src: require('./../../assets/Rathuadhab/views/view67.jpg'), caption: 'view 67' },
        view68: { src: require('./../../assets/Rathuadhab/views/view68.jpg'), caption: 'view 68' },
        view69: { src: require('./../../assets/Rathuadhab/views/view69.jpg'), caption: 'view 69' },
        view70: { src: require('./../../assets/Rathuadhab/views/view70.jpg'), caption: 'view 70' },
        view71: { src: require('./../../assets/Rathuadhab/views/view71.jpg'), caption: 'view 71' },
        view72: { src: require('./../../assets/Rathuadhab/views/view72.jpg'), caption: 'view 72' },

    },
    rooms: {
        room1: require('./../../assets/Rathuadhab/rooms/room1.jpg'),
        room2: require('./../../assets/Rathuadhab/rooms/room2.jpg'),
        room3: require('./../../assets/Rathuadhab/rooms/room3.jpg'),
        room4: require('./../../assets/Rathuadhab/rooms/room4.jpg'),
        room5: require('./../../assets/Rathuadhab/rooms/room5.jpg'),
        room6: require('./../../assets/Rathuadhab/rooms/room6.jpg'),
        room7: require('./../../assets/Rathuadhab/rooms/room7.jpg'),
    },
    locations: {
        location1: require('./../../assets/Rathuadhab/locationImages/location1.jpg'),
        location2: require('./../../assets/Rathuadhab/locationImages/location2.jpg'),
        location3: require('./../../assets/Rathuadhab/locationImages/location3.jpg'),
        location4: require('./../../assets/Rathuadhab/locationImages/location4.jpg'),
        location5: require('./../../assets/Rathuadhab/locationImages/location5.jpg'),
        location6: require('./../../assets/Rathuadhab/locationImages/location6.jpg')
    },
    general: require('./../../assets/Rathuadhab/headerBackground.jpg')
}

export default rathuadhab